[{"movieTitle":"Once Upon a Time... in Hollywood\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":1, "movieFunny":0, "movieAction":0, "movieRomance":0},
 {"movieTitle":"Star Wars: Episode IX - The Rise of Skywalker\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Avengers: Endgame\u00a0", "movieYear":2019, "movieRating":5, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Bad Boys for Life\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Trolls World Tour\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":1, "movieAction":0, "movieRomance":0},
 {"movieTitle":"Joker\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":1, "movieFunny":0, "movieAction":0, "movieRomance":0},
 {"movieTitle":"Bloodshot\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"The Godfather\u00a0", "movieYear":1972, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Jojo Rabbit\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":1, "movieAction":0, "movieRomance":0},
 {"movieTitle":"Onward\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":1, "movieFunny":1, "movieAction":0, "movieRomance":0},
 {"movieTitle":"Fantasy Island\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":1},
 {"movieTitle":"Jumanji: The Next Level\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Sonic the Hedgehog\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"The Irishman\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Dolittle\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":1, "movieFunny":1, "movieAction":0, "movieRomance":1},
 {"movieTitle":"Men in Black: International\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":1, "movieAction":0, "movieRomance":0},
 {"movieTitle":"Pulp Fiction\u00a0", "movieYear":1994, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Harry Potter and the Sorcerer's Stone\u00a0", "movieYear":2001, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Life of Pi\u00a0", "movieYear":2012, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Tenet\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":0, "movieRomance":1},
 {"movieTitle":"Avengers: Infinity War\u00a0", "movieYear":2018, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"The Lord of the Rings: The Fellowship of the Ring\u00a0", "movieYear":2001, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Thor: Ragnarok\u00a0", "movieYear":2017, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"The Lion King\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":1, "movieFunny":1, "movieAction":0, "movieRomance":0},
 {"movieTitle":"Mulan\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":1, "movieFunny":1, "movieAction":1, "movieRomance":1},
 {"movieTitle":"Suicide Squad\u00a0", "movieYear":2016, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":0, "movieRomance":1},
 {"movieTitle":"Blade Runner 2049\u00a0", "movieYear":2017, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Guardians of the Galaxy\u00a0", "movieYear":2014, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Angel Has Fallen\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Gladiator\u00a0", "movieYear":2000, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"The Matrix\u00a0", "movieYear":1999, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Frozen II\u00a0", "movieYear":2019, "movieRating":5, "movieComments":"", "movieSad":0, "movieFunny":1, "movieAction":0, "movieRomance":0},
 {"movieTitle":"Titanic\u00a0", "movieYear":1997, "movieRating":5, "movieComments":"", "movieSad":1, "movieFunny":0, "movieAction":0, "movieRomance":1},
 {"movieTitle":"Black Widow\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Spider-Man: Far from Home\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Wonder Woman 1984\u00a0", "movieYear":2020, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Jurassic World\u00a0", "movieYear":2015, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Jurassic Park\u00a0", "movieYear":1993, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Fight Club\u00a0", "movieYear":1999, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Se7en\u00a0", "movieYear":1995, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":1, "movieRomance":0},
 {"movieTitle":"Yesterday\u00a0", "movieYear":2019, "movieRating":4, "movieComments":"", "movieSad":0, "movieFunny":0, "movieAction":0, "movieRomance":1}]